//
//  SongAlbumInteractor.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongAlbumBusinessLogic
{
    func fetchAlbum(request: SongAlbum.FetchAlbum.Request)
}

protocol SongAlbumDataStore
{
    var albumId: Int { get set }
}

class SongAlbumInteractor: SongAlbumBusinessLogic, SongAlbumDataStore, SongAlbumWorkerDelegate
{
    var presenter: SongAlbumPresentationLogic?
    var worker = SongAlbumWorker()
    var albumId: Int = 0
    
    // MARK: Fetch Album
    
    func fetchAlbum(request: SongAlbum.FetchAlbum.Request)
    {
        worker.delegate = self
        worker.fetch(albumId: albumId)
    }
    
    func songAlbumWorker(songAlbumWorker: SongAlbumWorker, didFetchAlbum album: Album) {
        let response = SongAlbum.FetchAlbum.Response(album: album)
        presenter?.presentFetchedAlbum(response: response)
    }
}
