//
//  SongAlbumPresenter.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongAlbumPresentationLogic
{
    func presentSomething(response: SongAlbum.Something.Response)
}

class SongAlbumPresenter: SongAlbumPresentationLogic
{
    weak var viewController: SongAlbumDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: SongAlbum.Something.Response)
    {
        let viewModel = SongAlbum.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
