//
//  SongAlbumViewController.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongAlbumDisplayLogic: class
{
    func displayFetchedAlbum(viewModel: SongAlbum.FetchAlbum.ViewModel)
}

class SongAlbumViewController: UIViewController, SongAlbumDisplayLogic
{
    var interactor: SongAlbumBusinessLogic?
    var router: (NSObjectProtocol & SongAlbumRoutingLogic & SongAlbumDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SongAlbumInteractor()
        let presenter = SongAlbumPresenter()
        let router = SongAlbumRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = SongAlbum.FetchAlbum.Request()
        interactor?.fetchAlbum(request: request)
    }
    
    func displayFetchedAlbum(viewModel: SongAlbum.FetchAlbum.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
