//
//  SongAlbumPresenter.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongAlbumPresentationLogic
{
    func presentFetchedAlbum(response: SongAlbum.FetchAlbum.Response)
}

class SongAlbumPresenter: SongAlbumPresentationLogic
{
    weak var viewController: SongAlbumDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedAlbum(response: SongAlbum.FetchAlbum.Response)
    {
        let displayedAlbum = SongAlbum.FetchAlbum.ViewModel.DisplayedAlbum(name: "", artistName: "", albumArtworkUrl100: "", songs: [])
        let viewModel = SongAlbum.FetchAlbum.ViewModel(displayedAlbum: displayedAlbum)
        viewController?.displayFetchedAlbum(viewModel: viewModel)
    }
}
