//
//  SongAlbumInteractor.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongAlbumBusinessLogic
{
    func doSomething(request: SongAlbum.Something.Request)
}

protocol SongAlbumDataStore
{
    //var name: String { get set }
}

class SongAlbumInteractor: SongAlbumBusinessLogic, SongAlbumDataStore
{
    var presenter: SongAlbumPresentationLogic?
    var worker: SongAlbumWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: SongAlbum.Something.Request)
    {
        worker = SongAlbumWorker()
        worker?.doSomeWork()
        
        let response = SongAlbum.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
