//
//  SongAlbumPresenter.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongAlbumPresentationLogic
{
    func presentFetchedAlbum(response: SongAlbum.FetchAlbum.Response)
}

class SongAlbumPresenter: SongAlbumPresentationLogic
{
    weak var viewController: SongAlbumDisplayLogic?
    
    // MARK: Fetch Album
    
    func presentFetchedAlbum(response: SongAlbum.FetchAlbum.Response)
    {
        let album = response.album
        let displayedAlbum = SongAlbum.FetchAlbum.ViewModel.DisplayedAlbum(name: album.name, artistName: "Album by \(album.artistName)", albumArtworkUrl100: album.albumArtworkUrl100, songs: album.songs)
        let viewModel = SongAlbum.FetchAlbum.ViewModel(displayedAlbum: displayedAlbum)
        viewController?.displayFetchedAlbum(viewModel: viewModel)
    }
}
