//
//  SongAlbumModels.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SongAlbum
{
    // MARK: Use cases
    
    enum FetchAlbum
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel{
            struct DisplayedAlbum {
                var name: String
                var artistName: String
                var albumArtworkUrl100: String
                var songs: [Song]
            }
            var displayedAlbum: DisplayedAlbum
        }
    }
}
