//
//  SongSearchPresenterTests.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import FindYourSong
import XCTest

class SongSearchPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SongSearchPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupSongSearchPresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSongSearchPresenter()
    {
        sut = SongSearchPresenter()
    }
    
    // MARK: Test doubles
    
    class SongSearchDisplayLogicSpy: SongSearchDisplayLogic
    {
        var displaySomethingCalled = false
        
        func displayFetchedSongs(viewModel: SongSearch.FetchSongs.ViewModel)
        {
            displaySomethingCalled = true
        }
        
        var displayFetchedSongsCalled = false
        
        func displayFetchedSongsCalled(viewModel: SongSearch.FetchSongs.ViewModel) {
            displayFetchedSongsCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentFetchedSongsShouldAskViewControllerToFetchSongs()
    {
        // Given
        let songSearchDisplayLogicSpy = SongSearchDisplayLogicSpy()
        sut.viewController = songSearchDisplayLogicSpy
        let response = SongSearch.FetchSongs.Response()
        
        // When
        sut.presentFetchedSongs(response: response)
        
        // Then
        XCTAssertTrue(songSearchDisplayLogicSpy.displayFetchedSongsCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
