//
//  SongSearchInteractorTests.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import FindYourSong
import XCTest

class SongSearchInteractorTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SongSearchInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupSongSearchInteractor()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSongSearchInteractor()
    {
        sut = SongSearchInteractor()
    }
    
    // MARK: Test doubles
    
    class SongSearchPresentationLogicSpy: SongSearchPresentationLogic
    {
        var presentSomethingCalled = false
        
        func presentSomething(response: SongSearch.Something.Response)
        {
            presentSomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoSomething()
    {
        // Given
        let spy = SongSearchPresentationLogicSpy()
        sut.presenter = spy
        let request = SongSearch.Something.Request()
        
        // When
        sut.doSomething(request: request)
        
        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
