//
//  SongAlbumPresenterTests.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 28-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import FindYourSong
import XCTest

class SongAlbumPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SongAlbumPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupSongAlbumPresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSongAlbumPresenter()
    {
        sut = SongAlbumPresenter()
    }
    
    // MARK: Test doubles
    
    class SongAlbumDisplayLogicSpy: SongAlbumDisplayLogic
    {
        var displaySomethingCalled = false
        
        func displaySomething(viewModel: SongAlbum.Something.ViewModel)
        {
            displaySomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething()
    {
        // Given
        let spy = SongAlbumDisplayLogicSpy()
        sut.viewController = spy
        let response = SongAlbum.Something.Response()
        
        // When
        sut.presentSomething(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
