//
//  SendSongPresenterTests.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import FindYourSong
import XCTest

class SendSongPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SendSongPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupSendSongPresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSendSongPresenter()
    {
        sut = SendSongPresenter()
    }
    
    // MARK: Test doubles
//
//    class SendSongDisplayLogicSpy: SendSongDisplayLogic
//    {
//        var displaySomethingCalled = false
//
//        func displaySomething(viewModel: SendSong.SendSong.ViewModel)
//        {
//            displaySomethingCalled = true
//        }
//    }
//
//    // MARK: Tests
//
//    func testPresentSomething()
//    {
//        // Given
//        let spy = SendSongDisplayLogicSpy()
//        sut.viewController = spy
//        let response = SendSong.SendSong.Response()
//
//        // When
//        sut.presentSomething(response: response)
//
//        // Then
//        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//    }
}
