//
//  _SendSongInteractor.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendSongBusinessLogic
{
    func sendSong(request: SendSong.SendSong.Request)
}

protocol SendSongDataStore
{
    var songName: String { get set }
}

class SendSongInteractor: SendSongBusinessLogic, SendSongDataStore
{
    var presenter: SendSongPresentationLogic?
    var worker: SendSongWorker?
    var songName: String = ""
    
    // MARK: Send song
    
    func sendSong(request: SendSong.SendSong.Request)
    {
        worker =  SendSongWorker()
        worker?.doSomeWork()
        
        songName = request.songName
        let response = SendSong.SendSong.Response()
        presenter?.presentSendSong(response: response)
    }
}
