//
//  _SendSongPresenter.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendSongPresentationLogic
{
    func presentSendSong(response: SendSong.SendSong.Response)
}

class SendSongPresenter:  SendSongPresentationLogic
{
    weak var viewController: SendSongDisplayLogic?
    
    // MARK: Send song
    
    func presentSendSong(response: SendSong.SendSong.Response)
    {
        let viewModel = SendSong.SendSong.ViewModel()
        viewController?.sendSongToSearch(viewModel: viewModel)
    }
}
