//
//  SongSearchRouter.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SongSearchRoutingLogic
{
    func routeToSongAlbum(segue: UIStoryboardSegue?)
}

protocol SongSearchDataPassing
{
    var dataStore: SongSearchDataStore? { get }
}

class SongSearchRouter: NSObject, SongSearchRoutingLogic, SongSearchDataPassing
{
    weak var viewController: SongSearchViewController?
    var dataStore: SongSearchDataStore?
    
    //MARK: Routing
    
    func routeToSongAlbum(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! SongAlbumViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSongAlbum(source: dataStore!, destination: &destinationDS)
        } else {
            //let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "SongAlbumViewController") as! SongAlbumViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSongAlbum(source: dataStore!, destination: &destinationDS)
            navigateToSongAlbum(source: viewController!, destination: destinationVC)
        }
    }
    
    //MARK: Navigation
    
    func navigateToSongAlbum(source: SongSearchViewController, destination: SongAlbumViewController)
    {
        source.show(destination, sender: nil)
    }
    
    //MARK: Passing data
    
    func passDataToSongAlbum(source: SongSearchDataStore, destination: inout SongAlbumDataStore)
    {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.albumId = (source.songs?[selectedRow!].albumId)!
    }
}
