//
//  SongSearchPresenter.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongSearchPresentationLogic
{
    func presentFetchedSongs(response: SongSearch.FetchSongs.Response)
}

class SongSearchPresenter: SongSearchPresentationLogic
{
    weak var viewController: SongSearchDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedSongs(response: SongSearch.FetchSongs.Response)
    {
        //let viewModel = SongSearch.FetchSongs.ViewModel()
        //viewController?.displayFetchedSongs(viewModel: viewModel)
    }
}
