//
//  SongSearchInteractor.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongSearchBusinessLogic
{
    func doSomething(request: SongSearch.Something.Request)
}

protocol SongSearchDataStore
{
    //var name: String { get set }
}

class SongSearchInteractor: SongSearchBusinessLogic, SongSearchDataStore
{
    var presenter: SongSearchPresentationLogic?
    var worker: SongSearchWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: SongSearch.Something.Request)
    {
        worker = SongSearchWorker()
        worker?.doSomeWork()
        
        let response = SongSearch.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
