//
//  SongSearchWorker.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongSearchWorkerDelegate {
    func songSearchWorker(songSearchWorker: SongSearchWorker, didFetchSongs songs: [Song])
}

class SongSearchWorker: ItunesManagerDelegate
{
    var itunesManager: ItunesManager = ItunesManager()
    var delegate: SongSearchWorkerDelegate?
    
    func fetch(songName: String){
        itunesManager.delegate = self
        itunesManager.fetchSongs(songName: songName)
    }
    
    func itunesManager(itunesManager: ItunesManagerProtocol, didFetchSongs songs: [Song]) {
        delegate?.songSearchWorker(songSearchWorker: self, didFetchSongs: songs)
    }
}
