//
//  SongSearchInteractor.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongSearchBusinessLogic
{
    func fetchSongs(request: SongSearch.FetchSongs.Request)
}

protocol SongSearchDataStore
{
    var songName: String { get set }
}

class SongSearchInteractor: SongSearchBusinessLogic, SongSearchDataStore
{
    
    var presenter: SongSearchPresentationLogic?
    var worker = SongSearchWorker()
    var songName: String = ""
    
    // MARK: Do something
    
    func fetchSongs(request: SongSearch.FetchSongs.Request)
    {
        worker.fetch(songName: songName)
        
        //let response = SongSearch.FetchSongs.Response()
        //presenter?.presentFetchedSongs(response: response)
    }
}
