//
//  SongSearchViewController.swift
//  FindYourSong
//
//  Created by Fernando Garcia on 27-02-20.
//  Copyright (c) 2020 Fernando Garcia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class SongCell: UITableViewCell {
    @IBOutlet weak var songNameLabel: UILabel!
    @IBOutlet weak var artistNameLabel: UILabel!
    @IBOutlet weak var albumImage: UIImageView!
}

protocol SongSearchDisplayLogic: class
{
    func displayFetchedSongs(viewModel: SongSearch.FetchSongs.ViewModel)
}

class SongSearchViewController: UITableViewController, SongSearchDisplayLogic
{
    var interactor: SongSearchBusinessLogic?
    var router: (NSObjectProtocol & SongSearchRoutingLogic & SongSearchDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SongSearchInteractor()
        let presenter = SongSearchPresenter()
        let router = SongSearchRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        fetchSongs()
    }
    
    // MARK: Fetch Songs
    
    var displayedSongs: [SongSearch.FetchSongs.ViewModel.DisplayedSong] = []
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func fetchSongs()
    {
        let request = SongSearch.FetchSongs.Request()
        interactor?.fetchSongs(request: request)
    }
    
    func displayFetchedSongs(viewModel: SongSearch.FetchSongs.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
